# Generated by Django 4.1 on 2024-07-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "Application_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Application Id"
                    ),
                ),
                (
                    "Full_Name",
                    models.CharField(max_length=50, verbose_name="Full Name"),
                ),
                ("Date_of_birth", models.DateField(verbose_name="Date Of Birth")),
                (
                    "Highest_qualification",
                    models.CharField(
                        max_length=50, verbose_name="Highest Qualification"
                    ),
                ),
                ("Marks_obtained", models.IntegerField(verbose_name="Marks Obtained")),
                ("Goals", models.CharField(max_length=50, verbose_name="Goals")),
                (
                    "Email_id",
                    models.EmailField(max_length=254, verbose_name="Email Id"),
                ),
                (
                    "Scheduled_program_id",
                    models.IntegerField(verbose_name="Scheduled Program Id"),
                ),
                ("Status", models.CharField(max_length=50, verbose_name="Status")),
                (
                    "Date_Of_Interview",
                    models.DateField(verbose_name="Date Of Interview"),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "Application",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Roll_no", models.IntegerField(verbose_name="Roll No")),
                (
                    "Email_id",
                    models.EmailField(max_length=254, verbose_name="Email Id"),
                ),
                (
                    "Scheduled_program_id",
                    models.IntegerField(verbose_name="Scheduled Program Id"),
                ),
                (
                    "Application_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participant.application",
                        verbose_name="Application Id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "db_table": "Participant",
            },
        ),
    ]
