# Generated by Django 4.1 on 2024-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programs_Offered",
            fields=[
                (
                    "ProgramId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Program Id"
                    ),
                ),
                (
                    "ProgramName",
                    models.CharField(max_length=50, verbose_name="Program_Name"),
                ),
                (
                    "Description",
                    models.CharField(max_length=50, verbose_name="Description"),
                ),
                (
                    "Applicant_eligibility",
                    models.CharField(
                        max_length=30, verbose_name="Applicant Eligibility"
                    ),
                ),
                (
                    "Duration",
                    models.IntegerField(max_length=10, verbose_name="Duration"),
                ),
                (
                    "Degree_certificate_offered",
                    models.CharField(
                        max_length=20, verbose_name="Degree Certificate Offered"
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Offered",
                "verbose_name_plural": "Programs Offered",
                "db_table": "Programs Offered",
            },
        ),
        migrations.CreateModel(
            name="Programs_Scheduled",
            fields=[
                (
                    "Scheduled_program_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Scheduled Program Id",
                    ),
                ),
                (
                    "ProgramName",
                    models.CharField(max_length=50, verbose_name="Program Name"),
                ),
                ("Location", models.CharField(max_length=50, verbose_name="Location")),
                ("Start_Date", models.DateField(verbose_name="Start Date")),
                ("End_Date", models.DateField(verbose_name="End Date")),
                (
                    "sessions_per_week",
                    models.IntegerField(verbose_name="Sessions Per Week"),
                ),
            ],
            options={
                "verbose_name": "Program Scheduled",
                "verbose_name_plural": "Programs Scheduled",
                "db_table": "Programs Scheduled",
            },
        ),
    ]
