# Generated by Django 4.1 on 2024-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("login_id", models.CharField(max_length=50, verbose_name="Login ID")),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
                ("role", models.CharField(max_length=20, verbose_name="Role")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "User Data",
            },
        ),
    ]
