# Generated by Django 4.1 on 2024-08-02 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(
                default="Unknown",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email ID",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="first_name",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="last_name",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="login_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="Login ID"),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
        migrations.AlterModelTable(
            name="users",
            table="user_data",
        ),
    ]
