# Generated by Django 4.1 on 2024-08-02 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_users_email_users_first_name_users_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email ID",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
    ]
