# Generated by Django 4.1 on 2024-08-02 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_users_is_active_users_is_staff_users_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                default="Unknown",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email ID",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Last Name"
            ),
        ),
    ]
